# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Location', verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default=1, max_length=10, verbose_name='都道府県'),
            preserve_default=False,
        ),
    ]
