# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160225_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cleardata_privacy',
            field=models.IntegerField(default=1, verbose_name='クリアデータ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='player_name_privacy',
            field=models.IntegerField(default=1, verbose_name='プレイヤー名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_recently_privacy',
            field=models.IntegerField(default=1, verbose_name='最近更新した曲'),
        ),
    ]
