# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160229_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='プレミアムユーザー'),
        ),
    ]
