# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cleardata_privacy',
            field=models.IntegerField(default=1, help_text='プロフィールページにクリアデータを表示します。', verbose_name='クリアデータ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='player_name',
            field=models.CharField(blank=True, help_text='全角ひらがなカタカナ英数字6文字以内', max_length=6, null=True, verbose_name='プレイヤー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='player_name_privacy',
            field=models.IntegerField(default=1, help_text='ランキングにプレイヤー名とプロフィールページへのリンクが掲載されます。(非公開の場合は"匿名希望さん"と表示されます)', verbose_name='プレイヤー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='poputomo_id',
            field=models.CharField(blank=True, help_text='半角数字12文字', max_length=12, null=True, verbose_name='ポプともID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='premium',
            field=models.BooleanField(default=False, help_text='Amazonギフト券を買ってくれた人', verbose_name='プレミアムユーザー'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_recently_privacy',
            field=models.IntegerField(default=1, help_text='プロフィールページに最近更新した曲を表示します。', verbose_name='最近更新した曲'),
        ),
    ]
