# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='プレミアムユーザー限定', verbose_name='プレミアム'),
        ),
    ]
