# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_theme_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Theme', verbose_name='テーマ'),
        ),
    ]
