# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_premium',
        ),
    ]
