language: python
cache: pip
python:
  - 3.6
service: mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - python manage.py makemigrations main
  - python manage.py makemigrations users
  - python manage.py migrate
  - python manage.py test
notifications:
    slack: srandom:L4sBT2lWh9p7npl7NZJS4MU1
