language: python
cache: pip
python:
  - 3.9
services:
  - mysql
install:
  - pip install pipenv
  - pipenv install
before_script:
  - |
    echo -e "[mysqld]
    character_set_server=utf8mb4
    collation_server=utf8mb4_unicode_ci
    innodb_large_prefix=ON
    innodb_file_format=Barracuda
    innodb_file_format_max=Barracuda" | sudo tee /etc/mysql/conf.d/travis.cnf
  - sudo service mysql restart
  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - pipenv run python manage.py makemigrations main
  - pipenv run python manage.py makemigrations users
  - pipenv run python manage.py migrate
  - pipenv run python manage.py test
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
