language: python
cache: pip
python:
  - 3.6
service: mysql
install:
  - pip install -r requirements.txt
before_script:
  # to resolve: Index column size too large. The maximum column size is 767 bytes.
  - echo '[mysqld]' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_file_format=Barracuda' | sudo sh -c 'cat >> /etc/mysql/my.cnf'
  - echo 'innodb_file_per_table=1' | sudo sh -c 'cat >> /etc/mysql/my.cnf'
  - echo 'innodb_large_prefix=1' | sudo sh -c 'cat >> /etc/mysql/my.cnf'
  - sudo service mysql restart

  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - python manage.py makemigrations main
  - python manage.py makemigrations users
  - python manage.py migrate
  - python manage.py test
notifications:
    slack: srandom:L4sBT2lWh9p7npl7NZJS4MU1
