language: python
cache: pip
python:
  - 3.6
service: mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e "SET GLOBAL innodb_file_format=barracuda"
  - mysql -u root -e "SET GLOBAL innodb_file_per_table=ON"
  - mysql -u root -e "SET GLOBAL innodb_large_prefix=ON"
  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - python manage.py makemigrations main
  - python manage.py makemigrations users
  - python manage.py migrate
  - python manage.py test
notifications:
    slack: srandom:L4sBT2lWh9p7npl7NZJS4MU1
