version: "3"
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: srandom
      MYSQL_USER: srandom
      MYSQL_PASSWORD: srandom
      MYSQL_ROOT_PASSWORD: root
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    depends_on:
      - mysql
volumes:
  mysql_data:
    name: srandom_db_data
