version: "3"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: srandom
      POSTGRES_PASSWORD: srandom
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  db_data:
    name: srandom_postgres_data
