# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='BAD数')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'BAD数',
                'verbose_name': 'BAD数',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10, verbose_name='難易度')),
            ],
            options={
                'verbose_name_plural': '難易度',
                'verbose_name': '難易度',
            },
        ),
        migrations.CreateModel(
            name='Extra_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard', models.BooleanField(verbose_name='ハード')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Extra Option',
                'verbose_name': 'Extra Option',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='レベル')),
            ],
            options={
                'verbose_name_plural': 'レベル',
                'verbose_name': 'レベル',
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.IntegerField(verbose_name='クリアメダル')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'クリアメダル',
                'verbose_name': 'クリアメダル',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='曲名')),
                ('bpm', models.CharField(blank=True, max_length=10, null=True, verbose_name='BPM')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Difficulty', verbose_name='難易度')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Level', verbose_name='レベル')),
            ],
            options={
                'verbose_name_plural': '曲',
                'verbose_name': '曲',
            },
        ),
        migrations.CreateModel(
            name='Sran_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='S乱レベル')),
            ],
            options={
                'verbose_name_plural': 'S乱レベル',
                'verbose_name': 'S乱レベル',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='sran_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sran_Level', verbose_name='S乱レベル'),
        ),
        migrations.AddField(
            model_name='medal',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Music', verbose_name='曲'),
        ),
        migrations.AddField(
            model_name='medal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='extra_option',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Music', verbose_name='曲'),
        ),
        migrations.AddField(
            model_name='extra_option',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='bad_count',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Music', verbose_name='曲'),
        ),
        migrations.AddField(
            model_name='bad_count',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
