# Generated by Django 4.2.4 on 2023-11-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music', verbose_name='曲'),
        ),
        migrations.AlterField(
            model_name='bad_count',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music', verbose_name='曲'),
        ),
        migrations.AlterField(
            model_name='extra_option',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music', verbose_name='曲'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music', verbose_name='曲'),
        ),
        migrations.AlterField(
            model_name='news',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music', verbose_name='曲'),
        ),
    ]
