# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('kind', models.CharField(choices=[('A', '新規'), ('U', '更新'), ('D', '削除')], max_length=1)),
                ('status', models.BooleanField(default=True, verbose_name='状態')),
            ],
            options={
                'verbose_name_plural': 'News',
                'verbose_name': 'News',
            },
        ),
    ]
