# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160228_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_count',
            name='bad_count',
            field=models.PositiveIntegerField(verbose_name='BAD数'),
        ),
    ]
