# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Music', verbose_name='曲'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='kind',
            field=models.CharField(choices=[('新規', '新規'), ('レベル更新', 'レベル更新'), ('S乱レベル更新', 'S乱レベル更新'), ('削除', '削除')], max_length=10),
        ),
    ]
