# Generated by Django 4.2.4 on 2024-03-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activity_music_alter_bad_count_music_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
