# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160604_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='作成日'),
        ),
    ]
