# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160604_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(default=datetime.date(2016, 6, 4), verbose_name='作成日'),
        ),
    ]
