# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160604_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
