# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状態'),
        ),
    ]
