# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_activity_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'アクティビティ', 'verbose_name_plural': 'アクティビティ'},
        ),
    ]
