name: app

on: push

jobs:
  deploy:
#    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      SERVICE: app
      REGION: asia-northeast1
      IMAGE: asia-northeast1-docker.pkg.dev/srandom/app/app:${{ github.sha }}
    
    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Configure auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push a container
        run: |-
          git clone https://github.com/planetscale/django_psdb_engine.git
          ./scripts/decrypt-env.sh production
          docker build . -t ${{ env.IMAGE }}
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
